### ISSUE TITLE
Api no están llegando

### ISSUE THREAD

**Issue by nico01f** [OpenPulsar/multidata-api-clients#11]
Hola, solicité la generación de una API para consultar autos y no me llega. ¿Algo va mal?

**Comment by oscarvalenzuelab** [comment]
Hola, lo reviso en un par de horas. Es posible que este llegando a spam o que se haya renovado el certificado de conexion al servidor SMTP.

**Comment by nico01f** [comment]
Genial, espero al fix.

Saludos!

**Comment by oscarvalenzuelab** [comment]
te funciono?

**Comment by oscarvalenzuelab** [comment]
No respuesta. cerrando.
