### ISSUE TITLE
Consulta API Empresa

### ISSUE THREAD

**Issue by diurzuar** [OpenPulsar/multidata-api-clients#13]
Hola Oscar,

No he logrado recibir la API key para hacer la consulta de patentes.
Me gustaría poder conversar contigo para ver la posibilidad de trabajar con uds y quizás expandir el límite de consultas que tienen en la versión gratuita. 

Mi teléfono es el +569 4090 0875 

Saludos

**Comment by diurzuar** [comment]
Hola Oscar!
Por favor contactarme.

Saludos

**Comment by oscarvalenzuelab** [comment]
Te respondo por email. Salu2
